# Arrays Operations in Numpy

In [3]:
import numpy as np

In [6]:
zeros = np.zeros((2,2))
print(zeros)

[[0. 0.]
 [0. 0.]]


In [7]:
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
random = np.random.random(2)
print(random)

[0.9902916  0.51860596]
