### Array Properties

In [1]:
import numpy as np

arr = np.array([1.2, 2.5, 3.8])
int_arr = arr.astype(int)  # Convert to integer
print(int_arr)


[1 2 3]


In [2]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Convert to 2 rows, 3 columns
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)


[1 2 3 4 5 6]


In [4]:
arr = np.array([1, 2, 3, 4])
print(arr.sum())  # Output: 10


10


In [5]:
arr = np.array([1, 2, 3, 4])
print(arr.mean())  # Output: 2.5


2.5


In [6]:
arr = np.array([10, 20, 30, 40])
print(arr.max())  # Output: 40
print(arr.min())  # Output: 10


40
10


In [7]:
arr = np.array([3, 1, 4, 1, 5, 9])
arr.sort()
print(arr)  # Sorted array

[1 1 3 4 5 9]


In [8]:
arr = np.array([3, 1, 4, 1, 5, 9])
indices = arr.argsort()
print(indices)  # Indices of sorted elements


[1 3 0 2 4 5]


In [9]:
arr = np.array([[1, 2], [3, 4]])
transposed_arr = arr.transpose()
print(transposed_arr)


[[1 3]
 [2 4]]


In [10]:
arr = np.array([1, 2, 3])
copy_arr = arr.copy()
print(copy_arr)


[1 2 3]


In [11]:
arr = np.array([1, 2, 3])
list_arr = arr.tolist()
print(list_arr)  # Output: [1, 2, 3]


[1, 2, 3]


In [12]:
arr = np.array([0, 1, 0, 2, 3, 0])
indices = arr.nonzero()
print(indices)  # Output: (array([1, 3, 4]),)


(array([1, 3, 4]),)
