### Insertion and deletion in Numpy

In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40])
new_arr = np.insert(arr, 2, 25)  # Insert 25 at index 2
print(new_arr)  
# Output: [10 20 25 30 40]


[10 20 25 30 40]


In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = np.insert(arr, 1, [7, 8, 9], axis=0)  # Insert a new row at index 1
print(new_arr)


[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [3]:
arr = np.array([[1, 2], [3, 4]])
new_arr = np.insert(arr, 1, [9, 9], axis=1)  # Insert a column at index 1
print(new_arr)


[[1 9 2]
 [3 9 4]]


In [4]:
arr = np.array([10, 20, 30, 40, 50])
new_arr = np.delete(arr, 2)  # Remove element at index 2
print(new_arr)
# Output: [10 20 40 50]


[10 20 40 50]


In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
new_arr = np.delete(arr, 1, axis=0)  # Remove row at index 1
print(new_arr)


[[1 2 3]
 [7 8 9]]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = np.delete(arr, 1, axis=1)  # Remove column at index 1
print(new_arr)


[[1 3]
 [4 6]]
